language: java
jdk: oraclejdk7

before_install:
  - pip install codecov
  - sudo apt-get update -y
  - sudo apt-get install -y python-software-properties build-essential
  - sudo apt-get install -y libgd2-xpm ia32-libs ia32-libs-multiarch

after_success:
  - codecov