language: java
jdk: oraclejdk7

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python-software-properties build-essential
  - sudo apt-get install -y libgd2-xpm ia32-libs ia32-libs-multiarch

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: "APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | sed -n -e '/^\[.*\]/ !{ /^[0-9]/ { p; q } }')"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
       - "poker-helper-gui/dist/poker-helper-gui-$APP_VERSION-bin.zip"
  skip_cleanup: true
  on:
    tags: true